export const AppRoutes = {
    DEFAULT:'/',
    LOGIN:'/login',
    REGISTER:'/register',
    MAIN:'/main',
    JOURNAL:'/journal',
    INBOX:'/inbox',
    STUDENTS:'/students',
    SUBJECTS:'/subjects',
    SUBJECT_DETAILS: '/subjects/:subjectId',
    TASKS:'/tasks',
    SCHEDULE:'/schedule',
    CREATE_SUBJECT :'/create-subject',
    JOIN_SUBJECT: '/join-subject',
}