export const AppRoutes = {
    DEFAULT:'/',
    LOGIN:'/login',
    REGISTER:'/register',
    MAIN:'/main',
    JOURNAL:'/journal',
    INBOX:'/inbox',
    STUDENTS:'/students',
    SUBJECTS:'/subjects',
    SUBJECT_DETAILS: '/subjects/:subjectId',
    SCHEDULE:'/schedule',
    CREATE_SUBJECT :'/create-subject',
    JOIN_SUBJECT: '/join-subject',
    WEEKLY_GAME: '/weekly-game',
    STUDENT_GRADES: '/my-grades',
    STUDENT_TASKS: '/my-tasks',
    TASK_RESPONSES: '/tasks/:taskId/responses',
}